pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                echo "building"
            }
         }
          stage('test') {
            steps {
                echo "testing.. the applicaiton"
            }
         }
          stage('deploy') {
            steps {
                echo "deploying.. the application"
            }
         }
    }
}